// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (company, role_title, source, applied_date, current_stage)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company, role_title, source, applied_date, current_stage, created_at, updated_at
`

type CreateApplicationParams struct {
	Company      string      `json:"company"`
	RoleTitle    string      `json:"role_title"`
	Source       string      `json:"source"`
	AppliedDate  pgtype.Date `json:"applied_date"`
	CurrentStage string      `json:"current_stage"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.Company,
		arg.RoleTitle,
		arg.Source,
		arg.AppliedDate,
		arg.CurrentStage,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.RoleTitle,
		&i.Source,
		&i.AppliedDate,
		&i.CurrentStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, company, role_title, source, applied_date, current_stage, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.RoleTitle,
		&i.Source,
		&i.AppliedDate,
		&i.CurrentStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, company, role_title, source, applied_date, current_stage, created_at, updated_at FROM applications ORDER BY applied_date DESC
`

func (q *Queries) ListApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.RoleTitle,
			&i.Source,
			&i.AppliedDate,
			&i.CurrentStage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationStage = `-- name: UpdateApplicationStage :exec
UPDATE applications SET current_stage = $2, updated_at = now() WHERE id = $1
`

type UpdateApplicationStageParams struct {
	ID           pgtype.UUID `json:"id"`
	CurrentStage string      `json:"current_stage"`
}

func (q *Queries) UpdateApplicationStage(ctx context.Context, arg UpdateApplicationStageParams) error {
	_, err := q.db.Exec(ctx, updateApplicationStage, arg.ID, arg.CurrentStage)
	return err
}
