// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailMessageByGmailID = `-- name: GetEmailMessageByGmailID :one
SELECT id, gmail_message_id, gmail_thread_id, from_address, from_domain, subject, received_at, classified_label, classification_confidence, classification_source, matched_application_id, match_confidence, review_status, processed_at, created_at FROM email_messages WHERE gmail_message_id = $1
`

func (q *Queries) GetEmailMessageByGmailID(ctx context.Context, gmailMessageID string) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, getEmailMessageByGmailID, gmailMessageID)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.GmailMessageID,
		&i.GmailThreadID,
		&i.FromAddress,
		&i.FromDomain,
		&i.Subject,
		&i.ReceivedAt,
		&i.ClassifiedLabel,
		&i.ClassificationConfidence,
		&i.ClassificationSource,
		&i.MatchedApplicationID,
		&i.MatchConfidence,
		&i.ReviewStatus,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmailMessageIfNew = `-- name: InsertEmailMessageIfNew :one
INSERT INTO email_messages (gmail_message_id, gmail_thread_id, from_address, from_domain, subject, received_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (gmail_message_id) DO NOTHING
RETURNING id, gmail_message_id, gmail_thread_id, from_address, from_domain, subject, received_at, classified_label, classification_confidence, classification_source, matched_application_id, match_confidence, review_status, processed_at, created_at
`

type InsertEmailMessageIfNewParams struct {
	GmailMessageID string             `json:"gmail_message_id"`
	GmailThreadID  string             `json:"gmail_thread_id"`
	FromAddress    string             `json:"from_address"`
	FromDomain     string             `json:"from_domain"`
	Subject        string             `json:"subject"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertEmailMessageIfNew(ctx context.Context, arg InsertEmailMessageIfNewParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, insertEmailMessageIfNew,
		arg.GmailMessageID,
		arg.GmailThreadID,
		arg.FromAddress,
		arg.FromDomain,
		arg.Subject,
		arg.ReceivedAt,
	)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.GmailMessageID,
		&i.GmailThreadID,
		&i.FromAddress,
		&i.FromDomain,
		&i.Subject,
		&i.ReceivedAt,
		&i.ClassifiedLabel,
		&i.ClassificationConfidence,
		&i.ClassificationSource,
		&i.MatchedApplicationID,
		&i.MatchConfidence,
		&i.ReviewStatus,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}
