// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID           pgtype.UUID        `json:"id"`
	Company      string             `json:"company"`
	RoleTitle    string             `json:"role_title"`
	Source       string             `json:"source"`
	AppliedDate  pgtype.Date        `json:"applied_date"`
	CurrentStage string             `json:"current_stage"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmailMessage struct {
	ID                       pgtype.UUID        `json:"id"`
	GmailMessageID           string             `json:"gmail_message_id"`
	GmailThreadID            string             `json:"gmail_thread_id"`
	FromAddress              string             `json:"from_address"`
	FromDomain               string             `json:"from_domain"`
	Subject                  string             `json:"subject"`
	ReceivedAt               pgtype.Timestamptz `json:"received_at"`
	ClassifiedLabel          *string            `json:"classified_label"`
	ClassificationConfidence *float64           `json:"classification_confidence"`
	ClassificationSource     *string            `json:"classification_source"`
	MatchedApplicationID     pgtype.UUID        `json:"matched_application_id"`
	MatchConfidence          *float64           `json:"match_confidence"`
	ReviewStatus             string             `json:"review_status"`
	ProcessedAt              pgtype.Timestamptz `json:"processed_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	Snippet                  string             `json:"snippet"`
}

type OauthToken struct {
	ID                    int16              `json:"id"`
	Provider              string             `json:"provider"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	TokenType             string             `json:"token_type"`
	Expiry                pgtype.Timestamptz `json:"expiry"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type StageEvent struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	FromStage     string             `json:"from_stage"`
	ToStage       string             `json:"to_stage"`
	DetectedVia   string             `json:"detected_via"`
	SourceEmailID pgtype.UUID        `json:"source_email_id"`
	Confidence    *float64           `json:"confidence"`
	Note          string             `json:"note"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type SyncState struct {
	ID            int16              `json:"id"`
	LastHistoryID string             `json:"last_history_id"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
