// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, provider, access_token_encrypted, refresh_token_encrypted, token_type, expiry, updated_at FROM oauth_tokens WHERE id = 1
`

func (q *Queries) GetOAuthToken(ctx context.Context) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenType,
		&i.Expiry,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :exec
INSERT INTO oauth_tokens (id, provider, access_token_encrypted, refresh_token_encrypted, token_type, expiry, updated_at)
VALUES (1, $1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE SET
    provider                = EXCLUDED.provider,
    access_token_encrypted  = EXCLUDED.access_token_encrypted,
    refresh_token_encrypted = EXCLUDED.refresh_token_encrypted,
    token_type              = EXCLUDED.token_type,
    expiry                  = EXCLUDED.expiry,
    updated_at               = now()
`

type UpsertOAuthTokenParams struct {
	Provider              string             `json:"provider"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	TokenType             string             `json:"token_type"`
	Expiry                pgtype.Timestamptz `json:"expiry"`
}

func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, upsertOAuthToken,
		arg.Provider,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenType,
		arg.Expiry,
	)
	return err
}
