// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStageEvent = `-- name: InsertStageEvent :one
INSERT INTO stage_events (application_id, from_stage, to_stage, detected_via, source_email_id, confidence, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, application_id, from_stage, to_stage, detected_via, source_email_id, confidence, note, occurred_at
`

type InsertStageEventParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	FromStage     string      `json:"from_stage"`
	ToStage       string      `json:"to_stage"`
	DetectedVia   string      `json:"detected_via"`
	SourceEmailID pgtype.UUID `json:"source_email_id"`
	Confidence    *float64    `json:"confidence"`
	Note          string      `json:"note"`
}

func (q *Queries) InsertStageEvent(ctx context.Context, arg InsertStageEventParams) (StageEvent, error) {
	row := q.db.QueryRow(ctx, insertStageEvent,
		arg.ApplicationID,
		arg.FromStage,
		arg.ToStage,
		arg.DetectedVia,
		arg.SourceEmailID,
		arg.Confidence,
		arg.Note,
	)
	var i StageEvent
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromStage,
		&i.ToStage,
		&i.DetectedVia,
		&i.SourceEmailID,
		&i.Confidence,
		&i.Note,
		&i.OccurredAt,
	)
	return i, err
}

const listStageEventsForApplication = `-- name: ListStageEventsForApplication :many
SELECT id, application_id, from_stage, to_stage, detected_via, source_email_id, confidence, note, occurred_at FROM stage_events WHERE application_id = $1 ORDER BY occurred_at ASC
`

func (q *Queries) ListStageEventsForApplication(ctx context.Context, applicationID pgtype.UUID) ([]StageEvent, error) {
	rows, err := q.db.Query(ctx, listStageEventsForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StageEvent
	for rows.Next() {
		var i StageEvent
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.FromStage,
			&i.ToStage,
			&i.DetectedVia,
			&i.SourceEmailID,
			&i.Confidence,
			&i.Note,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
