// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncState = `-- name: GetSyncState :one
SELECT id, last_history_id, last_synced_at, updated_at FROM sync_state WHERE id = 1
`

func (q *Queries) GetSyncState(ctx context.Context) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.LastHistoryID,
		&i.LastSyncedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncState = `-- name: UpdateSyncState :exec
UPDATE sync_state SET last_history_id = $1, last_synced_at = $2, updated_at = now() WHERE id = 1
`

type UpdateSyncStateParams struct {
	LastHistoryID string             `json:"last_history_id"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateSyncState(ctx context.Context, arg UpdateSyncStateParams) error {
	_, err := q.db.Exec(ctx, updateSyncState, arg.LastHistoryID, arg.LastSyncedAt)
	return err
}
